In [10]:
import numpy as np
import sys


query_response_casted_list= [np.array([[0,0,0]]),np.array([[1,0,0]]),np.array([[0,1,0]]),np.array([[0,0,1]]),np.array([[1,1,0]]),np.array([[1,0,1]]),np.array([[0,1,1]]), np.array([[1,1,1]])]

PREDS_MAP_DICT = {
        '[[0 0 0]]': ['Not Classified'], 
        '[[1 0 0]]': ['Perfect'],  
        '[[0 1 0]]': ['EVN_NIA'],  
        '[[0 0 1]]': ['EVN_FPD'],  
        '[[0 1 1]]': ['EVN_NIA', 'EVN_FPD'],
        '[[1 1 1]]': ['Perfect'],
        '[[1 1 0]]': ['Perfect'],
        '[[1 0 1]]': ['Perfect'],
        }

In [8]:

for query_response_casted in query_response_casted_list:
    
    print(query_response_casted)
    print(sys.getsizeof(query_response_casted))

    #print(PREDS_MAP_DICT.get(str(query_response_casted)))
    #print(query_response_casted[0][0])
    #print(not query_response_casted[0].any())
    
    if query_response_casted[0][0] or not query_response_casted[0].any():
        print('No defects detected. Skipped.')
    else:
        label_names = PREDS_MAP_DICT.get(str(query_response_casted)) # list with the EVT_CODE
        print(f'Anomaly detected: {label_names}')

[[0 0 0]]
144
No defects detected. Skipped.
[[1 0 0]]
144
No defects detected. Skipped.
[[0 1 0]]
144
Anomaly detected: ['EVN_NIA']
[[0 0 1]]
144
Anomaly detected: ['EVN_FPD']
[[1 1 0]]
144
No defects detected. Skipped.
[[1 0 1]]
144
No defects detected. Skipped.
[[0 1 1]]
144
Anomaly detected: ['EVN_NIA', 'EVN_FPD']
[[1 1 1]]
144
No defects detected. Skipped.
